name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo step1
  call-workflow:
    uses: ./.github/workflows/B.yml
    secrets: inherit
