name: Reusable workflow example

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  test2:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: alibaba/cloud-native-test-ci-tool@v0.0.1
        name: test secrets
        with:
          action: "try"
          ask-config: "${{ secrets.token }}"
