on:
  pull_request:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to launch test
    steps:
      - name: Generate step summary
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      - name: Generate job summary
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_JOB_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_JOB_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_JOB_SUMMARY
          echo "- How about a third one?" >> $GITHUB_JOB_SUMMARY
