name: Second

on:
  workflow_run:
    workflows: ["First"]
    types:
      - completed

jobs:
  test2:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: apache/rocketmq-test-tool@1a646589accad17070423eabf0f54925e52b0666
        name: Deploy rocketmq
        with:
          action: "try"
          ask-config: "${{ secrets.ASK_CONFIG }}"
