name: Second

on:
  workflow_run:
    workflows: ["First"]
    types:
      - completed

jobs:
  test2:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: alibaba/cloud-native-test-ci-tool@939
        name: Deploy rocketmq
        with:
          action: "try"
          ask-config: "${{ secrets.ASK_CONFIG }}"
